### ISSUE TITLE
Model Data to a Json Array!

### ISSUE THREAD

**Issue by shine202** [SangeetaGulia/play-swagger-activator-template#1]
Hello,

I was just wondering how can I model the Data in the 'Model Schema' to be a Json Array instead of a Json Object like it shows!

From this :`
{
  "data": {
    "userId": 0,
    "username": "string",
    "language": "string",
    "email": "string"
 }
}`

to this : `
{
  "data": [
    "userId": 0,
    "username": "string",
    "language": "string",
    "email": "string"
  ]
}`

Thanks in advance.
Shine

**Comment by SangeetaGulia** [comment]
As you can see in this template examples, 'Model Schema' is coming as 'Json Object' because we have written toJson Method to convert my case class to that form.

For your case, you can provide definitions in your swagger.json file for that particular route as given below:

"definitions" : {
    "ArrayFormatResponse": {
      "type":"object",
      "required":[
        "data"
      ],
      "properties": {
        "data" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/models.User"
          }
        }
      }
    }
}
   


And for above definition, you can provide definitions in your routes response as ,

```
#"responses": {
#		"200": {
#			"description": "success",
#			"schema": {
#				"$ref": "#/definitions/ArrayFormatResponse"
#			}
#		}
#   }
```

**Comment by shine202** [comment]
Thanks, that works
